app:
    resource: '@AppBundle/Controller/'
    type: annotation
#Sans authentification
accueil1:
    path: /
    defaults: { _controller: AppBundle:Default:accueil}
accueil:
    path: /accueil
    defaults: { _controller: AppBundle:Default:accueil}
login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}
login_check:
    path: /login_check
logout:
    path: /logout
#Avec authentification
thematiques:
    path: /thematiques
    defaults: { _controller: AppBundle:Default:consulterThematiques}
questionnaires:
    path: /questionnaires
    defaults: { _controller: AppBundle:Default:consulterQuestionnaires}
questionnaire_voir:
    path:  /voirQuestionnaire/{id}
    defaults: { _controller: AppBundle:Default:voirQuestionnaire}
    requirements:
        id:  \d+
questionnaire_ajouter:
    path:  /ajouterQuestionnaire/{id}
    defaults: { _controller: AppBundle:Default:ajouterQuestionnaire}
    requirements:
        id:  \d+
questionnaire_supprimer:
    path:  /supprimerQuestionnaire/{id}
    defaults: { _controller: AppBundle:Default:delete}
    requirements:
        id:  \d+
questionnaire_list:
      path:  /listQuestionnaire/
      defaults: { _controller: AppBundle:Default:listQuestionnaire}

utilisateur:
    path: /utilisateur
    defaults: { _controller: AppBundle:Default:consulterUtilisateur}
