AppBundle\Entity\Examen:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ExamenRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
        note:
            type: float
            nullable: true
        rendu:
            type: boolean
    lifecycleCallbacks: {  }
    oneToMany:
      reponses:
        cascade: ["remove"]
        targetEntity: Reponse
        mappedBy: examen
    manyToOne:
      apprenant:
        targetEntity: Utilisateur
        inversedBy: examens_apprenant
        joinColumn:
          name: utilisateur_id
          referencedColumnName: id
      correcteur:
        targetEntity: Utilisateur
        inversedBy: examens_correcteur
        joinColumn:
          name: utilisateur_id
          referencedColumnName: id
