AppBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
    lifecycleCallbacks: {  }
